import Head from 'next/head'
import Image from 'next/image'
import { createClient } from "next-sanity";
import { useEffect, useRef, useLayoutEffect } from 'react';
import { gsap } from "gsap/dist/gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";

export default function Home({ pets }) {
  const mainRef = useRef()
  const ulRef = useRef()
  console.log(pets)

  useEffect(() => {
    gsap.registerPlugin(ScrollTrigger)

    const items = gsap.utils.toArray('.items');
  
    items.forEach((item, i) => {
      const anim = gsap.fromTo(item, {autoAlpha: 0 }, {duration: 0.8, autoAlpha: 1})

      ScrollTrigger.create({
        trigger: item,
        animation: anim,
        toggleActions: 'play none none none',
        once: true,
      })
    })
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main ref={mainRef}>
        <ul ref={ulRef}>
          {pets.map((pet, index) => (
              <li key={index} className='items'>
                <span>{pet.name} loves {pet.favFood}</span> <br/>
                <Image 
                  alt={pet.name}
                  loading="lazy" 
                  placeholder="blur"
                  blurDataURL={pet.blurDataURL.metadata.lqip}
                  src={`${pet.url}?w=1000&h=1000&dpr=2&auto=format&fit=crop`}
                  width={500} 
                  height={500} 
                  unoptimized={true}
                />
              </li>
          ))
          }
        </ul>
      </main>
    </>
  )
}

const client = createClient({
  projectId: "sjik838z",
  dataset: "production",
  apiVersion: "2022-03-25",
  useCdn: false
});

export async function getStaticProps() {
  const pets = await client.fetch(`*[_type == "pet"]{
    name, 
    favFood, 
    "url": photo.asset->url,
    "blurDataURL": photo.asset->{
      metadata {
        lqip
      }
    }
  }`)
  return {
    props: {
      pets
    }
  };
}